const Parallel = preload("res://addons/GDBehavior/Composite/Parallel.gd")
const Sequencer = preload("res://addons/GDBehavior/Composite/Sequencer.gd")
const SequencerMem = preload("res://addons/GDBehavior/Composite/SequencerMemory.gd")
const Selector = preload("res://addons/GDBehavior/Composite/Selector.gd")
const SelectorMem = preload("res://addons/GDBehavior/Composite/SelectorMemory.gd")
